# Generated by Django 3.0.3 on 2020-02-16 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20200216_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='username',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='active_chats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
