# Generated by Django 3.0.3 on 2020-02-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
